### ISSUE TITLE
add Required FW Version check

### ISSUE THREAD

**Issue by garoxas** [Bob123a1/CDNSP-GUI#1]
feature request to let user know if the downloaded NSP can be installed on specific firmware or not
this is for users who do not want to spend some time downloading NSP only to know that it cannot be run on their firmware (without patched RequiredSystemVersion of course)

I've implemented this on my fork https://github.com/garoxas/CDNSP-GUI/commit/c793030a0444e5eb98562d242360f912d39ce0dd
if you're interested to merge this into the main repo, please let me know

you need to toggle "Warn Required Firmware" or put "WarnFirmware": "True" in the config for it to work

![cdnsp1](https://user-images.githubusercontent.com/11901820/43990727-bee6a8b4-9d89-11e8-911f-98f270c4c436.PNG)
![cdnsp2](https://user-images.githubusercontent.com/11901820/43990728-c140c5ae-9d89-11e8-8aa6-420afc38fc16.PNG)

**Comment by Bob123a1** [comment]
Sorry it took some time for me to get back to you! I was thinking maybe I will just have this set for single downloads and not queued download, cause some user would queue download and leave it on overnight. 

What's your thought on this? Great idea btw ! Really nice

**Comment by garoxas** [comment]
that works too
glad you're interested. if you need any help just be sure to let me know
if you want, I can also spend some time on the weekend to implement my changes to your latest commit and make a PR afterwards
thanks

**Comment by Bob123a1** [comment]
@garoxas sure ! Thank you for your help, just merged another PR won't likely to charge the code for the time being

**Comment by garoxas** [comment]
#16 

firmware selection

![cdnsp1](https://user-images.githubusercontent.com/11901820/44298310-e2827100-a30a-11e8-903e-9961795c797f.PNG)

asking user confirmation. if user choose to install base+update+DLC it will check required firmware version for all of them, and will show the dialog even if only one of them require firmware version above of what set by user
firmware checking will be only done if user choose firmware version other than **Latest**, and as requested it will only affect single downloads

![cdnsp2](https://user-images.githubusercontent.com/11901820/44298312-e7472500-a30a-11e8-95b5-218953864893.PNG)

additional feature to retrieve required firmware version for games in queue

![cdnsp3](https://user-images.githubusercontent.com/11901820/44298344-69374e00-a30b-11e8-8bc0-ece9e490dfce.PNG)
![cdnsp4](https://user-images.githubusercontent.com/11901820/44298345-6b011180-a30b-11e8-8f31-81f8a19c2c11.PNG)
