### ISSUE TITLE
Mac osx 10.13.4 not show pop-up queue

### ISSUE THREAD

**Issue by Donas4Ceos** [Bob123a1/CDNSP-GUI#13]
Hi, if add a game to queue in the moment to click not show the pop-up queue

CDNSP-GUI 4.1.1
Python 3.7.0

**Comment by Bob123a1** [comment]
@Donas4Ceos check the ```CDNSP-GUI-config.json``` file, and check the value for "Queue_win", it should be ```"Queue_win": "620x300+1177+100"```

**Comment by Donas4Ceos** [comment]
Fix

Thanks Bob
