### ISSUE TITLE
Console mode possibility

### ISSUE THREAD

**Issue by jlozes** [Bob123a1/CDNSP-GUI#17]
Helo,

It could be intresting to propose also the command lines alternative to the GUI. I propose this because the GUI is totaly unusable for blind people on Windows (I'll test it on Linux when I'll have some time) (the screen reader have only access to the menu bar, the others things are unusable) and because this project seems to be the most updated and followed (CDNSP Next last version seems to be 1.9.4 and is one month old).

Thanks.

**Comment by Bob123a1** [comment]
Hello!

I will contact the developer of CDNSP_Next and make a PR (Pull Request) to that repo to update the script!

**Comment by jlozes** [comment]
Helo,

I've never found the CDNSP Next repository.

But I've found NUT, witch use command line and witch is updated and work perfectly for me.

Even if I can't use your CDNSP GUI, thanks for your hard work on this project. You can close this issue if you want or leave it open if, one day, you want to add this possibility to your project.

**Comment by Bob123a1** [comment]
Thanks! @jlozes and yup Nut is a great tool to replace CDNSP Next, since Next isn't supported anymore by the author
