### ISSUE TITLE
Error trying to download a game

### ISSUE THREAD

**Issue by kalleocarrilho** [Bob123a1/CDNSP-GUI#22]
I tried to download a game, but i get this message on CMD:

    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I think the server refuse the connection, theres any way that i can fix this??

**Comment by dev-hartmann** [comment]
Must be due to certificate being rejected, get the same exception but before there is this log output:
"Request rejected by server! Check your cert."

**Comment by joeypic** [comment]
I have the same message

**Comment by Bob123a1** [comment]
This has been fixed now, simply delete the "nx_tls_client_cert.pem" file in your GUI folder, and run the GUI app again, it will automatically fetch a working certificate for you!

**Comment by kalleocarrilho** [comment]
Thanks!!

**Comment by akileos** [comment]
Hello, having same issue. Was working fine this morning and suddenly stopped.
Server is https://superfly.hac.lp1.d4c.nintendo.net/ - when   accessing full /v1/t URL in browser getting access denied. Anything changed Nintendo side or my IP is banned ? 
Thanks.

**Comment by benbooth493** [comment]
I'm also suffering the same issue

**Comment by Dud3z** [comment]
same here

**Comment by akileos** [comment]
Made some research, the client certificate has been banned. Game over until someone finds a new way.

**Comment by Bob123a1** [comment]
Cert updated again, delete the cert and launch the GUI to automatically fetch the new one
