### ISSUE TITLE
pip3 command not working

### ISSUE THREAD

**Issue by BandarFHD** [Bob123a1/CDNSP-GUI#26]
I've looked everywhere for a solution but can't find any

When I open Python command line or IDLE and type [pip3 install requests pyopenssl tqdm unidecode Pillow] it gives me this error:

>>> pip3 install requests pyopenssl tqdm unidecode Pillow
  File "<stdin>", line 1
    pip3 install requests pyopenssl tqdm unidecode Pillow
               ^
SyntaxError: invalid syntax

The arrow is pointing at the word install

And I can't open the program because of that

**Comment by akileos** [comment]
You shouldn't run that in Python shell but on command line.

In python shell it would be something like that 
`
import pip
pip.main(['install', Pillow])
`

**Comment by BandarFHD** [comment]
Command line is giving me that error.

Now I tried the code you just mentioned and I keep getting this :(

>>> import pip
>>> pip.main(['install', 'Pillow'])
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    pip.main(['install', 'Pillow'])
AttributeError: module 'pip' has no attribute 'main'

**Comment by BandarFHD** [comment]
![455](https://user-images.githubusercontent.com/26187900/44612004-7ec9dd80-a80d-11e8-9a5b-6e9dea212a79.PNG)
![4555](https://user-images.githubusercontent.com/26187900/44612005-7ec9dd80-a80d-11e8-942c-8e2a0e96e8f7.PNG)

**Comment by akileos** [comment]
Try with 

> from pip._internal import main
> main(['install', 'Pillow'])

But easy way is to Start > run > cmd 
pip3 install requests pyopenssl tqdm unidecode Pillow

**Comment by BandarFHD** [comment]
It worked. Yet the program won't open :(
When I double click "CDNSP-GUI-Bob-v4.1.1.py" it opens quickly then closes. I can't catch any word except pip3.
And yes I downloaded the files from v4.1 and put them in one folder.

**Comment by BandarFHD** [comment]
Had to screen record to catch the error.
Here it is

![555666](https://user-images.githubusercontent.com/26187900/44612375-c30aad00-a810-11e8-9818-efc38d43a79b.PNG)

**Comment by BandarFHD** [comment]
I uninstalled python and did the whole thing again and it seems to be working.

Thanks for your help m8!

**Comment by akileos** [comment]
NP, Please close isssue.
