### ISSUE TITLE
request rejeckt by server!!!!

### ISSUE THREAD

**Issue by aradsd** [Bob123a1/CDNSP-GUI#27]
How can I fix this error?
![screenshot 1](https://user-images.githubusercontent.com/42689154/44615058-46160e00-a7e5-11e8-93fa-980339755cdc.png)

**Comment by akileos** [comment]
See #22 and close this issue.

**Comment by Bob123a1** [comment]
Cert updated again, delete the cert and launch the GUI to automatically fetch the new one
