### ISSUE TITLE
Cannot update title DB

### ISSUE THREAD

**Issue by TumnusB** [Bob123a1/CDNSP-GUI#32]
When attempting to update the title DB, Windows 10 is blocking the address used for the title keys and I have attempted everything to allow python and the website through the firewall even disabling it

**To Reproduce**
1. Go to update titlekeys
2. See Screenshot
![issue](https://user-images.githubusercontent.com/3604705/44793552-758a9900-ab9e-11e8-8676-e35776f0b2f2.png)

**Expected behavior**
The expected behaviour is to update or inform that I have the latest key database

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 61.0.2 (64-bit

**Comment by Bob123a1** [comment]
@TumnusB Are you able to access that link on your web browser ? If not your anti-virus software might be blocking the site

**Comment by TumnusB** [comment]
It's not the site the site works I've used a proxy and such to get to the .txt file but for some reason, windows, defender, doesn't agree with that site and is aggressively blocking it even when I turn my firewall and anti-virus off.
