### ISSUE TITLE
could you please add NSP verification like MD5 please?

### ISSUE THREAD

**Issue by u4113057** [Bob123a1/CDNSP-GUI#4]
could you please add NSP verification like MD5 please?
it would be very useful if i can be sure that the file i finished download is corrupt or not.

**Comment by Bob123a1** [comment]
I will double check if that's possible, from what I know since different downloader have different ways of repacking to NSP, the MD5 of one NSP may not match the MD5 of the other one

**Comment by 877cms** [comment]
@Bob123a1 @u4113057 it has already been done:
https://gbatemp.net/download/nspverify.35153/
