### ISSUE TITLE
Temp folder for downloads?

### ISSUE THREAD

**Issue by v9999** [Bob123a1/CDNSP-GUI#42]
**Is your feature request related to a problem? Please describe.**
No, it's just a feature that could be useful for mounted cloud drives.

**Describe the solution you'd like**
Mounted cloud drives use fuse subsystem to handle files. It's quite slower and it doesn't handle multiple read and write operations that well, neither does it fare well with multiple small files creation and removal.
It would be interesting if we could set two different folders: one for downloading the files and another for the final consolidated .nsp files.

**Describe alternatives you've considered**

**Additional context**
CDNSP 4.1.1
Python 3.6
Google Drive storage mounted with Rclone.

**Comment by Bob123a1** [comment]
Added the feature in v5 @v9999 !
