### ISSUE TITLE
Auto-Remove Older Versions of NSP files

### ISSUE THREAD

**Issue by IBNobody** [Bob123a1/CDNSP-GUI#43]
**Is your feature request related to a problem? Please describe.**
I have multiple versions of UPD updates my collection, eating up space. I only care about the latest UPD update files.

**Describe the solution you'd like**
It would be nice if there was an option to automatically purge older NSP update files if a new update is detected.

**Describe alternatives you've considered**
Manual deletion is painful on a large collection.

**Additional context**
None

**Comment by rockbass2560** [comment]
@Bob123a1 Do you need help with this feature?

**Comment by Bob123a1** [comment]
Sure @rockbass2560 that would be nice
