### ISSUE TITLE
Save queue just saves an empty file

### ISSUE THREAD

**Issue by timdonovanuk** [Bob123a1/CDNSP-GUI#44]
CDNSP 4.1.1 save queue just creates an nearly empty json file (simply contains '[]').

It would be great to be able to scan the download folder for part downloads to be able to resume. So many times I've queued a ton of stuff, CDNSP has stalled, and I then have to manually redownload them all again.

**Comment by Bob123a1** [comment]
Save queue should automatically add the games added to queue to the CDNSP_queue.json file (I think that's the file name)

**Comment by timdonovanuk** [comment]
Where might this file be? It doesn't get generated for me anywhere in the folder. Clicking save queue opens a save file dialog.

**Comment by Bob123a1** [comment]
@timdonovanuk it should be in the folder called "Config"

Just tested it, added a game into my queue and it automatically added the game into the CDNSP_queue.json file as well 

![image](https://user-images.githubusercontent.com/19917682/45389394-e8504580-b66f-11e8-9139-ee0de270ee5f.png)
