### ISSUE TITLE
Adding a specific version to download queue doesn't work, always downloads latest version

### ISSUE THREAD

**Issue by PSXDupe** [Bob123a1/CDNSP-GUI#46]
I think the issue is in this piece of code, but I'm not a Python developer. From what I can understand, the code should return the latest version number if "Latest" is passed in as ver, and should return the same value that was passed if not "Latest"

However, this code always returns the latest version number, therefore you cannot queue an older version.

    def process_item_versions(self, tid, ver):
        if _("Latest") or "Latest" in ver:
            if tid.endswith('000'):
                tid = '%s800' % tid[:-3]
            ver = get_versions(tid)[-1]
        elif "none" in ver:
            ver = "none"
        return (tid, ver)

**Comment by garoxas** [comment]
Yep, actually I've addressed it in my PR
You can fix it yourself by modifying the .py following this commit

https://github.com/Bob123a1/CDNSP-GUI/pull/16/commits/db35fa77a8d09c7952cda7aa9c77c3caabf1f756

**Comment by Bob123a1** [comment]
Fixed with v5
