### ISSUE TITLE
No Demo and No Japanese Game is broken since Version 5

### ISSUE THREAD

**Issue by ferris1000** [Bob123a1/CDNSP-GUI#47]
If i click on No Demo and No Japanese Game nothing happen since Version 5, the Demos and Japanese Games will be still displayed. This funktion worked up to version 4.1.1 without any issues.
i tried a fresh Downloaded Version but it doesn't work either.

**Comment by crwusiz** [comment]
cdnsp mode
no demo , no japanese game filter not running

but nut mode running ok..

source fix..plz~

**Comment by ericjwg** [comment]
change game[1] into game[2] in below codes:   

 def make_list(self):
        # Create list in advance
        self.full_list = self.current_status
        if current_mode_global == "CDNSP":
            self.no_demo_list = []  # No demo list
            for game in self.full_list:
                if "demo" not in game[2].strip().lower(
                ) and "体験版" not in game[2].strip().lower():
                    self.no_demo_list.append(game)

            self.no_jap_list = []
            for game in self.full_list:
                try:
                    game[2].strip().lower().encode(
                        encoding='utf-8').decode('ascii')
                except UnicodeDecodeError:
                    pass
                else:
                    self.no_jap_list.append(game)

            self.no_demo_jap_list = []
            for game in self.full_list:
                if "demo" not in game[2].strip().lower(
                ) and "体験版" not in game[2].strip().lower():
                    try:
                        game[1].strip().lower().encode(
                            encoding='utf-8').decode('ascii')
                    except UnicodeDecodeError:
                        pass
                    else:
                        self.no_demo_jap_list.append(game)

**Comment by Bob123a1** [comment]
Fixed in v5.0.1
