### ISSUE TITLE
{Feature Request} download new titles

### ISSUE THREAD

**Issue by Ninjistix** [Bob123a1/CDNSP-GUI#52]
a way to add all new titles (not demos's to the queue to make them easier to dl).

**Comment by Wolf4Life** [comment]
It already there after updating titlekey and version list under download if wanted. Just sort by state and select all new and add to queue. If you don't want demos just check the no demo box and it they don't go away uncheck and recheck and look again.

**Comment by Gamer4Life2020** [comment]
It is already there after updating titlekey and version list under download if wanted. Just sort by state and select all new and add to queue. If you don't want demos just check the no demo box and it they don't go away uncheck and recheck and look again.

**Comment by Ninjistix** [comment]
okay maybe my issue isn't really clear, I get that the update title key button adds titles as new, if if I download then new titles and then I add all of the games again to the queue and download all game/dlc/updates again, it still downloads new updates

**Comment by Ninjistix** [comment]
with cdn dead ill go ahead and close this 🗡
