### ISSUE TITLE
hactool_linux not found

### ISSUE THREAD

**Issue by ikerib** [Bob123a1/CDNSP-GUI#58]
**Describe the bug**
On linux, when I click in a game to get the info and stuff I got an error:
`Exception: b'/bin/sh: 1: ./hactool_linux: not found'. Code: 127`

**To Reproduce**
1. Just click in on game

**Expected behavior**
Download game info

**Desktop (please complete the following information):**
 - Ubuntu Mate 16.04
 - I have a valid cert

**Comment by Bob123a1** [comment]
You most likely have to change your current directory to the GUI folder path @ikerib

**Comment by ikerib** [comment]
how?

**Comment by Bob123a1** [comment]
cd path/to/folder 

See here: http://www.linfo.org/cd.html

**Comment by Bob123a1** [comment]
@ikerib it should be bundled with my v5 release

**Comment by ikerib** [comment]
Ok... I see now the problem.... every mayor update you release everthing... then only the script and whatever is needed.

Thanks
