### ISSUE TITLE
Cert rejected by server

### ISSUE THREAD

**Issue by dev-hartmann** [Bob123a1/CDNSP-GUI#59]
Cert seems to be banned. 

![screen shot 2018-09-20 at 10 08 24 am](https://user-images.githubusercontent.com/9327242/45804751-3d6a0800-bcbd-11e8-9346-659c040c7b30.png)

**Comment by Bob123a1** [comment]
Yes it is, you would need to find a new working one

Leaving this issue up so the same question doesn't get asked again in the future

**Comment by blizzardxennor** [comment]
Hey, where we can find another cert? Thanks and keep up the good work
