### ISSUE TITLE
MacOS X Mojave no graphic on buttons 

### ISSUE THREAD

**Issue by dakiz71** [Bob123a1/CDNSP-GUI#64]
CDNSP 5.02
worked like a charm on High Sierra (after following the troubleshooting guide for Mac posted here),
still works like a charm on Mojave but there is no more any graphic on buttons to add to queue, download and update title keys

I've added a screenshot to explain better.
<img width="1267" alt="schermata 2018-09-24 alle 21 38 03" src="https://user-images.githubusercontent.com/43312596/45974909-0ee48800-c043-11e8-95f7-b06214f35093.png">

**Comment by Bob123a1** [comment]
@dakiz71 Could be a bug in macOS Mojave, haven't updated to Mojave myself so will be unable to test for that bug. Are there other people with similar problems updating to Mojave?

**Comment by CarterLi** [comment]
Mine is much worse.

![image](https://user-images.githubusercontent.com/6134068/46052837-a85e8780-c172-11e8-8e70-71cec8643bce.png)

The graphic is totally black but it seems that controls are still there because I can see the cursor changes when I'm moving my mouse

**Comment by Heatway** [comment]
<img width="1250" alt="snipaste_2018-09-27_22-40-48" src="https://user-images.githubusercontent.com/6970479/46153854-85cd8b00-c2a6-11e8-9de2-7262047ae095.png">
I can't see the download option on MacOS X Mojave
