### ISSUE TITLE
New Cert - The old is rejected by server

### ISSUE THREAD

**Issue by Viox-LJ** [Bob123a1/CDNSP-GUI#66]
Hi guys, im try to use this, but the cert is banned or blocked... Is possible change this cert? Anyone have a new valid cert?

Is impossible to use without a valid Cert?

BR
Santiago

**Comment by Ch0cola** [comment]
No more CDN downloads, N implement a new system that check if you own the game before download, try new certs only instaban it.

**Comment by Viox-LJ** [comment]
Ah ok... Therefore this application no longer works. Any alternative to download the games on Pc?

**Comment by Viox-LJ** [comment]
> No more CDN downloads, N implement a new system that check if you own the game before download, try new certs only instaban it.

Ah ok... Therefore this application no longer works. Any alternative to download the games on Pc?

**Comment by caiofcabral** [comment]
> > No more CDN downloads, N implement a new system that check if you own the game before download, try new certs only instaban it.
> 
> Ah ok... Therefore this application no longer works. Any alternative to download the games on Pc?

https://t.me/switchnsps

https://t.me/switchroms

**Comment by RaspberryEqualsPi** [comment]
open
