### ISSUE TITLE
CDNSP-GUI is dead?

### ISSUE THREAD

**Issue by matbeavis** [Bob123a1/CDNSP-GUI#68]
Can the program still work? Maybe sometime in the future or is dead once and for all? It was a simpler way to download in great speed and quality, I hope the developers can fix it.

Sorry for the bad writing english is not my first language.

**Comment by Bob123a1** [comment]
I am working on an alternative download method, although we most likely can't download directly from Nintendo anymore, we would still have ways to easily download games without needing to click through hundreds of ads

**Comment by matbeavis** [comment]
Thank you for your reply, CDNSP-GUI came in handy in many moments and even without Nintendo servers direct download it will still be more easy than torrent files. I'm excited for the new version, my best wishes good luck!
