### ISSUE TITLE
spam in console while opening

### ISSUE THREAD

**Issue by BASgamer** [Bob123a1/CDNSP-GUI#71]
**when i open it starts off with**
"Current language: en

Checking if all required modules are installed!

Everything looks good!"

**Then it spams** 
"Check if there's extra spaces at the bottom of your titlekeys.txt file! Delete if you do!"

**the it says**
"Status: Done!

GUI Version: 6.0.0
Language Files Version: 1.0.1"

I checked my titlekeys.txt and it didnt end have a blank space at the end
Even checked titlekeys_overwrite.txt and Nut_titlekeys.txt
Title keys update normally when you use the button and i dont think it did this the first time i opened it.
seems to operate fine just wanted to report this as a minor annoyance so far shown that at least darkest dungeon has an update i need

**Comment by BASgamer** [comment]
The problem went away. did you fix something on your end? this and my other post arent doing it any more so they can be closed

**Comment by BASgamer** [comment]
is it an issue with title keys format i see some titles listed as length
01009c00098420000000000000000005
then some as 
01005c700990a000
would that cause any issues? didnt really see that in the nut tickets

**Comment by Bob123a1** [comment]
Issue should be fixed in v6.0.1 as well, can you please confirm this ? @BASgamer

**Comment by Bob123a1** [comment]
Yeah that's something I forgot to mention, it will be good to delete the existing titlekey files, thanks for your support!

**Comment by Bob123a1** [comment]
And thanks for all your report ! Sorry that it took some time for me to push this release out to fix them
