### ISSUE TITLE
updating titlekey issue

### ISSUE THREAD

**Issue by BASgamer** [Bob123a1/CDNSP-GUI#76]
Unable to update title keys through button. It says may be down or unavailable. Thinking its an issue with the snip url forwarder. When you go to the page it now has a proceed button to click to get to the page that might be the issue always used to autoforward for me before hand.

**Comment by Bob123a1** [comment]
Can confirm that is indeed the problem, I will fix this issue in a few hours when I get home !

**Comment by BASgamer** [comment]
seems to be working now. the site isnt doing it anymore. guess i should have waited 48 hours instead of the 24 i did to see if the site fixed itself

**Comment by Bob123a1** [comment]
Yeah it seems like snip.li was playing around with their links, surprised that they reverted the change

**Comment by erpazzo78** [comment]
Quindi per farlo funzionare?grazie

Il Lun 29 Ott 2018, 11:34 Bob <notifications@github.com> ha scritto:

**Comment by erpazzo78** [comment]
Un modo per farlo funzionare esiste o è solo così per informazioni

Il Lun 29 Ott 2018, 11:45 gianluca marchese <erpazzo1978@gmail.com> ha
scritto:
