### ISSUE TITLE
title key update bug

### ISSUE THREAD

**Issue by BASgamer** [Bob123a1/CDNSP-GUI#77]
Sometimes when i update the title keys with the button the new game window includes 1300+ games. Is there a bug in comparing new and old since swapping to the new title keys format? Happened in nut mode this time(didnt look what mode it was in when its happened before), ill try to see if when it happens if its in cdnsp mode too.

**Comment by BASgamer** [comment]
its still showing me just 1 new title though so just a cosmetic thing atm i think

**Comment by Bob123a1** [comment]
Yeah like you said it is to do with how the program compares the old and new database, most likely due to recent changes to the format of the database. I will edit the program and hopefully that will show a more accurate representation
