### ISSUE TITLE
CDNSP-GUI-Bob.py unable to lunch/run after python latest version installed on win 10

### ISSUE THREAD

**Issue by GitHubNoobie** [Bob123a1/CDNSP-GUI#79]
Hello

CDNSP-GUI-Bob.py is unable to lunch/run on win 10. python latest 3.7 version installed
I followed all the installation, steps.

here below the message I got when trying to run the*.py file

![image](https://user-images.githubusercontent.com/39349551/48941222-f1387f80-ef1a-11e8-908b-182ba80b303b.png)

**Comment by Bob123a1** [comment]
Get the files from my v6 release, you would need those
