### ISSUE TITLE
HTTP Error 404: Not found

### ISSUE THREAD

**Issue by Denver3D** [Bob123a1/CDNSP-GUI#80]
Hello everyone,

I'm sorry but I'm facing a weird bug right now, I've downloaded Python 3.7 and the pack released for CDNSP-GUI but still each time I launch the CDNSP python file I got this weird  error, I even tried with a vpn but still I got this error

Current language: en

Checking if all required modules are installed!

Unable to get required files! Check your internet connection: [HTTP Error 404: Not Found]

I've also Formated my computer again and still same error, ofc I'm plugged with cable and I don't have any anti virus or firewall instead of the firewall of windows 10 but that also I've disabled it and still same error .... I'm going to be crazy

**Comment by TheLastZombie** [comment]
404 means that the requested resource can't be found on the server, i.e. the file does not exist. [Six days ago](https://github.com/Bob123a1/CDNSP-GUI-Files/commits/master), some files were removed from the CDNSP-GUI-Files repository, so that is probably the reason why it fails. The only one I can think of, anyway.

**Comment by Bob123a1** [comment]
@TheLastZombie that is indeed correct. I'll see if I can upload the required files somewhere.

**Comment by Denver3D** [comment]
Oh soo what should I do please ? :(

**Comment by OreoCupcakes** [comment]
The files still exist on GitHub as GitHub keeps a copy of it even if Bob deletes it. Look through the commits of Dec 4th and you'll find the files needed. Just click on the commit, then click View File, Raw, then just copy paste it.

**Comment by dbw-holic** [comment]
Hi @OreoCupcakes , thanks for your suggestion. I have just fetched the required files from the older commit history. However, when running the 6.0.1.py file, the program was stopped by this line: `UnboundLocalError: local variable '_tid' referenced before assignment`
Any idea? 

For reference, these are the codes displayed on the Terminal
```
iMac-2:CDNSP weidavid$ python3 CDNSP-GUI-Bob-v6.0.1.py
Current language: en

Checking if all required modules are installed!


Everything looks good!

Building the current state list... Please wait, this may take some time depending on how many games you have.
Check if there's extra spaces at the bottom of your titlekeys.txt file! Delete if you do!
Traceback (most recent call last):
  File "CDNSP-GUI-Bob-v6.0.1.py", line 4367, in <module>
    main()
  File "CDNSP-GUI-Bob-v6.0.1.py", line 4362, in main
    Application(root, titleID_list, titleKey_list, title_list, dbURL, info_list=info_list)
  File "CDNSP-GUI-Bob-v6.0.1.py", line 2006, in __init__
    self.update_list(rebuild=True)
  File "CDNSP-GUI-Bob-v6.0.1.py", line 2165, in update_list
    titleID_list, titleKey_list, title_list, info_list = read_titlekey_list()
  File "CDNSP-GUI-Bob-v6.0.1.py", line 4304, in read_titlekey_list
    if len(_tid) == 16:
UnboundLocalError: local variable '_tid' referenced before assignment
```

**Comment by Bob123a1** [comment]
I have added a link with the files you will require on the homepage README file, please check that out.
