### ISSUE TITLE
no file CDNSP-GUI-config.json

### ISSUE THREAD

**Issue by md5xwl** [Bob123a1/CDNSP-GUI#84]
File "CDNSP-GUI-Bob.py", line 65, in <module>
    f = open("CDNSP-GUI-config.json", 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'CDNSP-GUI-config.json'

**Comment by victory7** [comment]
same problem

**Comment by adiif1** [comment]
I have same problem .. i use 6.0.1

**Comment by Bob123a1** [comment]
I have added a link with the files you will require on the homepage README file, please check that out. @md5xwl @victory7 @adiif1
