### ISSUE TITLE
Please be sure to check, how to get the token

### ISSUE THREAD

**Issue by LiuNianAndMorty** [Bob123a1/CDNSP-GUI#96]
Hello there:
I am a game planner from China. In China, because we don't have similar software, the cost of getting the game is relatively high. After using your software, we can get the game very conveniently. Of course, due to some concerns, you canceled it. For this project, we can't get the latest game updates, which is very regrettable, but I know through some channels that you can make your program available again by extracting your own certificate, but this requires edge.token and edge_token.txt Two files, I know that some people are profiting by converting these two files, and the validity period of the documents is only one day. I would like to ask if you are willing to help, can you tell me how to convert tokens, we are China has launched a similar project to sort all the NSP files and distribute them to the players for download. Thank you very much!

**Comment by ThatNerdyPikachu** [comment]
Please see #97.
